#!/usr/bin/with-contenv bash

if [ ! -d "/config/users/MainUsers/crushadmin" ]; then
  
   exec \
   s6-setuidgid abc java -jar /config/CrushFTP.jar -a "crushadmin" "password" \
    echo crushadmin created \
    chown -R abc:abc \
	/config
fi
exec \
 s6-setuidgid abc java -jar /config/CrushFTP.jar -d


