#!/usr/bin/with-contenv bash

if [ ! -d "/var/opt/CrushFTP8_PC/users/MainUsers/crushadmin" ]; then
  
   exec \
   s6-setuidgid abc java -jar CrushFTP.jar -a "crushadmin" "password" \
    echo crushadmin created
fi
exec \
 s6-setuidgid abc java -jar CrushFTP.jar -d


